<a href="https://colab.research.google.com/github/NhuY26/HM_B1/blob/main/B%C3%A0i_1_Vector_v%C3%A0_Ma_tr%E1%BA%ADn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Cho v là 1 vector hàng
v = [1, 2, 3, 4, 5]

In [2]:
v = np.array([1,2,3,4,5])
print(v)

[1 2 3 4 5]


Cho w là 1 vcetor cột
w = [1; 2; 3; 4; 5]

In [3]:
w = np.array([[1],
              [2],
              [3],
              [4],
              [5]])
print(w)

[[1]
 [2]
 [3]
 [4]
 [5]]


(Hãy xác định số chiều (ndim), kích thước
(shape) của 2 vector v và w; In 2 vector v và w
ra màn hình; Nhận xét điểm khác biệt của kết
quả)

In [4]:
print("số chiều vector v: ", v.ndim)
print("kích thước vector v: ", v.shape)
print("số chiều vector w: ", w.ndim)
print("kích thước vector w: ", w.shape)
print("vector v: ", v)
print("vector w: \n", w)


số chiều vector v:  1
kích thước vector v:  (5,)
số chiều vector w:  2
kích thước vector w:  (5, 1)
vector v:  [1 2 3 4 5]
vector w: 
 [[1]
 [2]
 [3]
 [4]
 [5]]


Cho u và w là 2 vector cột có kích thước
(m, 1). Hãy tạo ma trận X bằng cách
ghép 2 vector cột u và w lại với nhau
X = [u, w]

In [5]:
u = np.array([[7],
              [8],
              [9],
              [10],
              [6]])
X = np.hstack((u,w))
print("số chiều X: ", X.ndim)
print("kích thước X: ", X.shape)
print(X)

số chiều X:  2
kích thước X:  (5, 2)
[[ 7  1]
 [ 8  2]
 [ 9  3]
 [10  4]
 [ 6  5]]


Hãy tạo ma trận X

In [6]:
X = np.array([[1,2,3,4,5],
             [6,7,8,9,2],
             [4,5,7,2,1]])
Y = np.reshape(X , (3,5))
print(X)
print(Y)
print("Số chiều: ", X.ndim)
print("Kích thước: ", X.shape)

[[1 2 3 4 5]
 [6 7 8 9 2]
 [4 5 7 2 1]]
[[1 2 3 4 5]
 [6 7 8 9 2]
 [4 5 7 2 1]]
Số chiều:  2
Kích thước:  (3, 5)


Hãy nhân ma trận X với vector v

In [7]:
Xv = np.dot(X, v)
print("Chiều: ", Xv.ndim)
print("Kích thước: ", Xv.shape)
print(Xv)

Chiều:  1
Kích thước:  (3,)
[55 90 48]


Hãy nhân ma trận X với vector w

In [8]:
Xw = np.dot(X, w)
print("Chiều: ", Xw.ndim)
print("Kích thước: ", Xw.shape)
print(Xw)

Chiều:  2
Kích thước:  (3, 1)
[[55]
 [90]
 [48]]


Xét ma trận X ở câu 5, hãy tìm ma trận
chuyển vị của X, ký hiệu là X
T

In [9]:
print("Ma trận chuyển vị: \n", X.T)

Ma trận chuyển vị: 
 [[1 6 4]
 [2 7 5]
 [3 8 7]
 [4 9 2]
 [5 2 1]]
